### ISSUE TITLE
ESP32 sending values to Serial.print

### ISSUE THREAD

**Issue by SimonCS10** [olliiiver/sml_parser#1]
Hi @olliiiver,
first of all thanks a lot for providing this SML Parser. I kind of got it running on an ESP32 for reading an ISKRA MT681. When sending the values to the serial, I get pretty strange behaviour. The first 5 digits are the correct kWh of the smart meter and I assume that also some other digits belong the transmitted power. But the length of the value is pretty strange. From translating the HEX value into DEC and using the Scaler 1/10 I know that the transmitted data reads as 11293590,2 Wh. Do you have an idea what might have happened?

dtostrf(MomentanWh, 10, 1, floatBuffer);
Serial.print("Leistung Momentan in Wh: ");
Serial.println(floatBuffer);

>>> Successfully received a complete message!
Wirkenergie Bezug Gesamt in Wh: 112935902000000010225733149127336218953132629394531250000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000.0

Guru Meditation Error: Core  1 panic'ed (LoadProhibited). Exception was unhandled.
Core 1 register dump:
PC      : 0x40143fe2  PS      : 0x00060030  A0      : 0x800d1465  A1      : 0x3ffb1ab0  
A2      : 0x30353231  A3      : 0xffffffff  A4      : 0x00000100  A5      : 0x3f400298  
A6      : 0x0000000d  A7      : 0x00000001  A8      : 0x3ffb1a40  A9      : 0x0000000d  
A10     : 0x00e832c0  A11     : 0x3ffb1a40  A12     : 0x00000007  A13     : 0x00000000  
A14     : 0x00000007  A15     : 0x3ffb1964  SAR     : 0x0000001f  EXCCAUSE: 0x0000001c  
EXCVADDR: 0x00e832c0  LBEG    : 0x400029ac  LEND    : 0x400029cb  LCOUNT  : 0x00000000  

ELF file SHA256: 0000000000000000

Backtrace: 0x40143fe2:0x3ffb1ab0 0x400d1462:0x3ffb1ad0 0x400d16e1:0x3ffb1b00 0x400d1799:0x3ffb1f50 0x400d32b9:0x3ffb1f70 0x400d1967:0x3ffb1f90 0x400d42f1:0x3ffb1fb0 0x4008985e:0x3ffb1fd0

Rebooting...

Also, I tried to read the current value:
1-0:16.7.0*255 | Wirkleistung in W
by adding the Handler {0x01, 0x00, 0x10, 0x07, 0x00, 0xff}, &LeistungMomentan}, but it only reads -1 and lots of zeros.

Best regards,
Simon

**Comment by olliiiver** [comment]
Seems you're reading data from an invalid memory location.

See https://docs.espressif.com/projects/esp-idf/en/latest/esp32/api-guides/fatal-errors.html

Since you are getting a complete SML message and the core panic comes right after your output, I think the error must be there...
