### ISSUE TITLE
Possible integration for ST STM32 CubeIDE ?

### ISSUE THREAD

**Issue by nobrainer-de** [olliiiver/sml_parser#3]
Hey i found your SML Parser from volkszaehler. I am experimenting with a stm32 (seeed E5) and try to implement your parser.
Did you try something else before? Any hints?

Got some problems with the C++ integration in C (header file), not that familiar with stm32 at all, just at beginning. Could it be interesting if i can find a implementation for this?

![grafik](https://user-images.githubusercontent.com/60841834/184419320-d07788b1-ed45-4b07-8bfc-add733e30456.png)

**Comment by olliiiver** [comment]
Hi. Have not tested the lib on stm32, but it should work there as well ...
